--------------------------------------------------------
-- Archivo creado  - lunes-enero-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OP_CIUDAD
--------------------------------------------------------

  CREATE TABLE "ANLYT"."OP_CIUDAD" 
   (	"CIUDAD_ID" NUMBER(4,0), 
	"PAIS" VARCHAR2(30 BYTE), 
	"COD_DEPARTAMENTO" NUMBER(4,0), 
	"NOMBRE_DEPARTAMENTO" VARCHAR2(30 BYTE), 
	"COD_MUNICIPIO" NUMBER(4,0), 
	"NOMBRE_MUNICIPIO" VARCHAR2(30 BYTE), 
	"LATITUD" NUMBER(9,6), 
	"LONGITUD" NUMBER(9,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OP_EMPRESA
--------------------------------------------------------

  CREATE TABLE "ANLYT"."OP_EMPRESA" 
   (	"EMPRESA_ID" NUMBER(9,0), 
	"NIT" VARCHAR2(20 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OP_EVENTO
--------------------------------------------------------

  CREATE TABLE "ANLYT"."OP_EVENTO" 
   (	"EVENTO_ID" NUMBER(16,0), 
	"EVENTO_TIPO" VARCHAR2(10 BYTE), 
	"EVENTO_FECHA" DATE, 
	"EVENTO_DIRECCION_IP" VARCHAR2(20 BYTE), 
	"EVENTO_CANAL" VARCHAR2(20 BYTE), 
	"EVENTO_RESP_NROCONFIRMACION" NUMBER(16,0), 
	"EVENTO_RESP_COD" VARCHAR2(20 BYTE), 
	"EVENTO_RESP_DESCRIPCION" VARCHAR2(256 BYTE), 
	"COMERCIO_COD" VARCHAR2(20 BYTE), 
	"CAJA_ID" VARCHAR2(20 BYTE), 
	"TX_ORIGEN_CUENTA" VARCHAR2(20 BYTE), 
	"TX_DESTINO_CUENTA" VARCHAR2(20 BYTE), 
	"CAJERO_ID" VARCHAR2(20 BYTE), 
	"BONO_SERIAL" VARCHAR2(20 BYTE), 
	"BONO_ESPECIE_COD" VARCHAR2(20 BYTE), 
	"BONO_EMISOR_COD" VARCHAR2(20 BYTE), 
	"BONO_ESPECIE_VER" VARCHAR2(20 BYTE), 
	"BONO_ESTADO" VARCHAR2(20 BYTE), 
	"BONO_VALOR" NUMBER(16,2), 
	"BONO_DENOMINACION" VARCHAR2(256 BYTE), 
	"BONO_FECHA_VENCIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_TIPO" IS '"E1:EmisionCompletada,E2:TransferenciaAgregadorRealizada,E3:TransferenciaEmpresarioRealizada,E4:RedencionRealizada"';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_FECHA" IS 'fecha en la cual se ejecutó el evento en la plataforma (la boveda)
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_DIRECCION_IP" IS 'direccion ip de la maquina donde se hace la redencion
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_CANAL" IS 'canal a traves del cual se solicitó la ejecución del evento dominio: DATAFONO, APPMOVIL, APPWEB,PLATAFORMA_GOFIVE,PORTAL
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_RESP_NROCONFIRMACION" IS 'numero de confirmacion de la transaccion efectuada y confirmada
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_RESP_COD" IS 'codigo de respuesta enviada por la boveda
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."EVENTO_RESP_DESCRIPCION" IS 'mensaje de feedback enviado por la boveda
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."COMERCIO_COD" IS 'codigo que identifica univocamente al comercio que redime
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."CAJA_ID" IS 'caja donde se redime
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."TX_ORIGEN_CUENTA" IS 'cuenta origen de la transaccion (redencion: de la persona que redime)
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."TX_DESTINO_CUENTA" IS 'codigo que identifica a la cuenta destino de la transaccion (redención: del comercio donde se redime)
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."CAJERO_ID" IS 'codigo que identifica el cajero donde se redime
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_SERIAL" IS 'numero serial del bono (S/N)
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_ESPECIE_COD" IS 'codigo que identifica al comercio-emisor del bono
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_EMISOR_COD" IS 'dato del bono que identifica la especie bajo la que fue emitida
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_ESPECIE_VER" IS 'dato del bono que identifica la version de especie bajo la que fue emitida
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_ESTADO" IS 'dominio: CREADO,ALMACENADO,DISPONIBLE,ACTIVO,REDIMIDO,VENCIDO,ANULADO
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_VALOR" IS 'valor del bono 
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_DENOMINACION" IS 'identifica la denominacion del bono 
';
   COMMENT ON COLUMN "ANLYT"."OP_EVENTO"."BONO_FECHA_VENCIMIENTO" IS 'fecha en la cual se vence el bono
';
--------------------------------------------------------
--  DDL for Table OP_REDENCION_CAJERO
--------------------------------------------------------

  CREATE TABLE "ANLYT"."OP_REDENCION_CAJERO" 
   (	"CAJERO_ID" VARCHAR2(20 BYTE), 
	"NOMBRES_CAJERO" VARCHAR2(50 BYTE), 
	"PRIMER_APELLIDO_CAJERO" VARCHAR2(30 BYTE), 
	"SEGUNDO_APELLIDO_CAJERO" VARCHAR2(30 BYTE), 
	"SUCURSAL_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OP_SUCURSAL
--------------------------------------------------------

  CREATE TABLE "ANLYT"."OP_SUCURSAL" 
   (	"SUCURSAL_ID" VARCHAR2(20 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(200 BYTE), 
	"LATITUD" NUMBER(9,6), 
	"LONGITUD" NUMBER(9,6), 
	"CIUDAD_ID" NUMBER(4,0), 
	"EMPRESA_ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ANLYT.OP_CIUDAD
SET DEFINE OFF;
REM INSERTING into ANLYT.OP_EMPRESA
SET DEFINE OFF;
REM INSERTING into ANLYT.OP_EVENTO
SET DEFINE OFF;
Insert into ANLYT.OP_EVENTO (EVENTO_ID,EVENTO_TIPO,EVENTO_FECHA,EVENTO_DIRECCION_IP,EVENTO_CANAL,EVENTO_RESP_NROCONFIRMACION,EVENTO_RESP_COD,EVENTO_RESP_DESCRIPCION,COMERCIO_COD,CAJA_ID,TX_ORIGEN_CUENTA,TX_DESTINO_CUENTA,CAJERO_ID,BONO_SERIAL,BONO_ESPECIE_COD,BONO_EMISOR_COD,BONO_ESPECIE_VER,BONO_ESTADO,BONO_VALOR,BONO_DENOMINACION,BONO_FECHA_VENCIMIENTO) values ('3889','E4',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ANLYT.OP_EVENTO (EVENTO_ID,EVENTO_TIPO,EVENTO_FECHA,EVENTO_DIRECCION_IP,EVENTO_CANAL,EVENTO_RESP_NROCONFIRMACION,EVENTO_RESP_COD,EVENTO_RESP_DESCRIPCION,COMERCIO_COD,CAJA_ID,TX_ORIGEN_CUENTA,TX_DESTINO_CUENTA,CAJERO_ID,BONO_SERIAL,BONO_ESPECIE_COD,BONO_EMISOR_COD,BONO_ESPECIE_VER,BONO_ESTADO,BONO_VALOR,BONO_DENOMINACION,BONO_FECHA_VENCIMIENTO) values ('3890','E4',to_date('24/01/16','DD/MM/RR'),'127.0.0.1','APPMOVIL','503890','EVT_OK','transaccion al peluche','0054','CAJA_ADMIN',null,null,'ADMIN','803890',null,null,null,'ACTIVO','20000',null,to_date('31/01/16','DD/MM/RR'));
Insert into ANLYT.OP_EVENTO (EVENTO_ID,EVENTO_TIPO,EVENTO_FECHA,EVENTO_DIRECCION_IP,EVENTO_CANAL,EVENTO_RESP_NROCONFIRMACION,EVENTO_RESP_COD,EVENTO_RESP_DESCRIPCION,COMERCIO_COD,CAJA_ID,TX_ORIGEN_CUENTA,TX_DESTINO_CUENTA,CAJERO_ID,BONO_SERIAL,BONO_ESPECIE_COD,BONO_EMISOR_COD,BONO_ESPECIE_VER,BONO_ESTADO,BONO_VALOR,BONO_DENOMINACION,BONO_FECHA_VENCIMIENTO) values ('1','E4',to_date('24/01/16','DD/MM/RR'),'127.0.0.1','APPMOVIL','0','0',null,'GRANESTACION_CORRAL','GE_1','JMGOYES_CTA1','CORRAL_CTA1','GE_1_CAJERO_1','1','BONOS_20MIL','CORRAL','1.0','REDIMIDO',null,'20000',to_date('31/01/17','DD/MM/RR'));
REM INSERTING into ANLYT.OP_REDENCION_CAJERO
SET DEFINE OFF;
REM INSERTING into ANLYT.OP_SUCURSAL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CIUDAD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."PK_CIUDAD_ID" ON "ANLYT"."OP_CIUDAD" ("CIUDAD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_CIUDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."UK_CIUDAD" ON "ANLYT"."OP_CIUDAD" ("COD_DEPARTAMENTO", "COD_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EMPRESA_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."PK_EMPRESA_ID" ON "ANLYT"."OP_EMPRESA" ("EMPRESA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_NIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."UK_NIT" ON "ANLYT"."OP_EMPRESA" ("NIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CAJERO_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."PK_CAJERO_ID" ON "ANLYT"."OP_REDENCION_CAJERO" ("CAJERO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SUCURSAL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."PK_SUCURSAL_ID" ON "ANLYT"."OP_SUCURSAL" ("SUCURSAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_SUCURSAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANLYT"."UK_SUCURSAL" ON "ANLYT"."OP_SUCURSAL" ("RAZON_SOCIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OP_CIUDAD
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_CIUDAD" ADD CONSTRAINT "UK_CIUDAD" UNIQUE ("COD_DEPARTAMENTO", "COD_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_CIUDAD" ADD CONSTRAINT "PK_CIUDAD_ID" PRIMARY KEY ("CIUDAD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_CIUDAD" MODIFY ("CIUDAD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OP_EMPRESA
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_EMPRESA" ADD CONSTRAINT "UK_NIT" UNIQUE ("NIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_EMPRESA" ADD CONSTRAINT "PK_EMPRESA_ID" PRIMARY KEY ("EMPRESA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_EMPRESA" MODIFY ("RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_EMPRESA" MODIFY ("NIT" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_EMPRESA" MODIFY ("EMPRESA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OP_EVENTO
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_EVENTO" MODIFY ("EVENTO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OP_REDENCION_CAJERO
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_REDENCION_CAJERO" ADD CONSTRAINT "PK_CAJERO_ID" PRIMARY KEY ("CAJERO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_REDENCION_CAJERO" MODIFY ("SUCURSAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_REDENCION_CAJERO" MODIFY ("CAJERO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OP_SUCURSAL
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_SUCURSAL" ADD CONSTRAINT "UK_SUCURSAL" UNIQUE ("RAZON_SOCIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_SUCURSAL" ADD CONSTRAINT "PK_SUCURSAL_ID" PRIMARY KEY ("SUCURSAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ANLYT"."OP_SUCURSAL" MODIFY ("EMPRESA_ID" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_SUCURSAL" MODIFY ("CIUDAD_ID" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_SUCURSAL" MODIFY ("RAZON_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "ANLYT"."OP_SUCURSAL" MODIFY ("SUCURSAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OP_REDENCION_CAJERO
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_REDENCION_CAJERO" ADD CONSTRAINT "FK_CAJERO_SUCURSAL" FOREIGN KEY ("SUCURSAL_ID")
	  REFERENCES "ANLYT"."OP_SUCURSAL" ("SUCURSAL_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OP_SUCURSAL
--------------------------------------------------------

  ALTER TABLE "ANLYT"."OP_SUCURSAL" ADD CONSTRAINT "FK_SUCURSAL_CIUDAD" FOREIGN KEY ("CIUDAD_ID")
	  REFERENCES "ANLYT"."OP_CIUDAD" ("CIUDAD_ID") ENABLE;
  ALTER TABLE "ANLYT"."OP_SUCURSAL" ADD CONSTRAINT "FK_SUCURSAL_EMPRESA" FOREIGN KEY ("EMPRESA_ID")
	  REFERENCES "ANLYT"."OP_EMPRESA" ("EMPRESA_ID") ENABLE;
