----------------------------------------------------------------------

-- # create importation table



  CREATE TABLE "BVRD1_OLAP"."DEMO_BULKDATA" 
   (	"CODIGOEMISION" VARCHAR2(30 BYTE), 
	"NEMOTECNICO" VARCHAR2(10 BYTE), 
	"CODIGOISIN" VARCHAR2(15 BYTE), 
	"FECHAEMISION" DATE, 
	"FECHAVENCIMIENTO" DATE, 
	"FECHALIQUIDACION" DATE, 
	"MONTO_EMITIDO" NUMBER(20,4), 
	"INVERSIONMINIMA" NUMBER(8,0), 
	"INVERSIONMAXIMA" NUMBER(8,0), 
	"TIPOTASA" VARCHAR2(20 BYTE), 
	"TIPOLIQUIDACION" VARCHAR2(40 BYTE), 
	"CUPON" NUMBER(10,2), 
	"FECHAINICIOCOLOCACION" DATE, 
	"FECHAFINALCOLOCACION" DATE, 
	"CODIGOINTERNO" VARCHAR2(5 BYTE), 
	"EMISOR" VARCHAR2(200 BYTE), 
	"BASELIQUIDACION" VARCHAR2(20 BYTE), 
	"NOMBREINSTRUMENTO" VARCHAR2(100 BYTE), 
	"MONEDA" VARCHAR2(4 BYTE), 
	"FECHAHORAGENERACION" DATE, 
	"INDUSTRIA" VARCHAR2(200 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"DESCRIPCIONEMISION" VARCHAR2(1000 BYTE), 
	"SPREAD" NUMBER(6,2), 
	"FECHAULTIMACALIFICACION" DATE, 
	"CALIFICACION" VARCHAR2(5 BYTE), 
	"DESCRIPCIONCALIFICACION" VARCHAR2(100 BYTE), 
	"TIPOEMISOR" VARCHAR2(10 BYTE), 
	"TIPOPERIODOCODIGO" NUMBER(4,0), 
	"FECHA_OPER" DATE, 
	"DIAS_ACUM" NUMBER(5,0), 
	"DIAS_ALVENCI" NUMBER(5,0), 
	"VALOR_NOM_UNIT" NUMBER(20,4), 
	"CANT_TIT" NUMBER(12,0), 
	"VALOR_NOM_TOT" NUMBER(20,4), 
	"PRECIO_LIMP" NUMBER(20,4), 
	"VALOR_TRAN" NUMBER(20,4), 
	"YIELD" NUMBER(20,4), 
	"MERCADO" NUMBER(4,0), 
	"NEMO_INS" VARCHAR2(10 BYTE), 
	"CANTIDADOPERACIONES" NUMBER(5,0), 
	"NOMBREMERCADO" VARCHAR2(400 BYTE), 
	"VRTRANSADOEQUIVDOP" NUMBER(20,4), 
	"VRTRANSADOEQUIVUSD" NUMBER(20,4), 
	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DEMOBULKDATA" PRIMARY KEY ("ID")
   );
   
create sequence seq_DEMOBULKDATA_id start with 1 increment by 1;
